export interface PossibleTypesResultData {
  possibleTypes: {
    [key: string]: string[];
  };
}
const result: PossibleTypesResultData = {
  possibleTypes: {
    CartError: ['CartItemError', 'CouponError', 'ShippingMethodError'],
    Commenter: ['CommentAuthor', 'User'],
    ContentNode: [
      'ExternalProduct',
      'GroupProduct',
      'MediaItem',
      'Page',
      'Post',
      'ProductVariation',
      'SimpleProduct',
      'VariableProduct',
    ],
    ContentRevisionUnion: ['Post', 'Page'],
    ContentTemplate: ['DefaultTemplate'],
    DatabaseIdentifier: [
      'Category',
      'Comment',
      'MediaItem',
      'Menu',
      'MenuItem',
      'PaColor',
      'PaMaterial',
      'PaPaperWeight',
      'PaSize',
      'Page',
      'Post',
      'PostFormat',
      'ProductCategory',
      'ProductTag',
      'ProductType',
      'ShippingClass',
      'Tag',
      'User',
      'VisibleProduct',
    ],
    EnqueuedAsset: ['EnqueuedScript', 'EnqueuedStylesheet'],
    HierarchicalContentNode: ['MediaItem', 'Page'],
    HierarchicalTermNode: ['Category', 'ProductCategory'],
    MenuItemLinkable: ['Category', 'Page', 'Post', 'ProductCategory', 'ProductTag', 'Tag'],
    MenuItemObjectUnion: ['Post', 'Page', 'Category', 'Tag', 'ProductCategory', 'ProductTag'],
    Node: [
      'Category',
      'Comment',
      'CommentAuthor',
      'ContentType',
      'Coupon',
      'Customer',
      'EnqueuedScript',
      'EnqueuedStylesheet',
      'ExternalProduct',
      'GroupProduct',
      'MediaItem',
      'Menu',
      'MenuItem',
      'Order',
      'PaColor',
      'PaMaterial',
      'PaPaperWeight',
      'PaSize',
      'Page',
      'Plugin',
      'Post',
      'PostFormat',
      'ProductCategory',
      'ProductTag',
      'ProductType',
      'ProductVariation',
      'Refund',
      'ShippingClass',
      'ShippingMethod',
      'SimpleProduct',
      'Tag',
      'TaxRate',
      'Taxonomy',
      'Theme',
      'User',
      'UserRole',
      'VariableProduct',
      'VisibleProduct',
    ],
    NodeWithAuthor: ['MediaItem', 'Page', 'Post'],
    NodeWithComments: [
      'ExternalProduct',
      'GroupProduct',
      'MediaItem',
      'Order',
      'Page',
      'Post',
      'SimpleProduct',
      'VariableProduct',
    ],
    NodeWithContentEditor: [
      'ExternalProduct',
      'GroupProduct',
      'Page',
      'Post',
      'SimpleProduct',
      'VariableProduct',
    ],
    NodeWithExcerpt: ['Post'],
    NodeWithFeaturedImage: [
      'ExternalProduct',
      'GroupProduct',
      'Page',
      'Post',
      'ProductVariation',
      'SimpleProduct',
      'VariableProduct',
    ],
    NodeWithPageAttributes: ['Page'],
    NodeWithRevisions: ['Page', 'Post'],
    NodeWithTemplate: ['MediaItem', 'Page', 'Post'],
    NodeWithTitle: ['MediaItem', 'Page', 'Post'],
    NodeWithTrackbacks: ['Post'],
    PostObjectUnion: ['Post', 'Page', 'MediaItem'],
    Product: ['ExternalProduct', 'GroupProduct', 'SimpleProduct', 'VariableProduct'],
    ProductAttribute: ['GlobalProductAttribute', 'LocalProductAttribute'],
    TermNode: [
      'Category',
      'PaColor',
      'PaMaterial',
      'PaPaperWeight',
      'PaSize',
      'PostFormat',
      'ProductCategory',
      'ProductTag',
      'ProductType',
      'ShippingClass',
      'Tag',
      'VisibleProduct',
    ],
    TermObjectUnion: [
      'Category',
      'Tag',
      'PostFormat',
      'ProductType',
      'VisibleProduct',
      'ProductCategory',
      'ProductTag',
      'ShippingClass',
      'PaColor',
      'PaMaterial',
      'PaPaperWeight',
      'PaSize',
    ],
    UniformResourceIdentifiable: [
      'Category',
      'ContentType',
      'ExternalProduct',
      'GroupProduct',
      'MediaItem',
      'Page',
      'Post',
      'PostFormat',
      'ProductCategory',
      'ProductTag',
      'ProductVariation',
      'ShippingClass',
      'SimpleProduct',
      'Tag',
      'User',
      'VariableProduct',
    ],
  },
};
export default result;
